options:
  dynamic_substitutions: true

substitutions:
  _IMAGE_NAME: europe-west1-docker.pkg.dev/${PROJECT_ID}/single-page-application
  _SERVICE_NAME: single-page-application

steps:
  - id: build
    name: gcr.io/cloud-builders/docker
    dir: installation-app
    args:
      - build
      - -t
      - $_IMAGE_NAME:dev
      - .

  - id: push
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - $_IMAGE_NAME
      - --all-tags

  - id: deploy
    name: gcr.io/cloud-builders/gcloud
    entrypoint: gcloud
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - --image
      - $_IMAGE_NAME:dev
      - --region
      - europe-west1
