options:
  dynamic_substitutions: true

substitutions:
  _IMAGE_NAME: ${LOCATION}-docker.pkg.dev/${PROJECT_ID}/docker/bff
  _SERVICE_NAME: bff


steps:
  - id: build
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - $_IMAGE_NAME:prod
      - -f
      - $_SERVICE_NAME/Dockerfile
      - .

  - id: push
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - $_IMAGE_NAME
      - --all-tags

  - id: deploy
    name: gcr.io/cloud-builders/gcloud
    entrypoint: gcloud
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - --image
      - $_IMAGE_NAME:prod
      - --region
      - europe-west1
